# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "lukemurraynz"
    assignees:
      - "lukemurraynz"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    # Group related updates together
    groups:
      azure-packages:
        patterns:
          - "Azure.*"
        update-types:
          - "minor"
          - "patch"
      testing-packages:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "coverlet*"
          - "FluentAssertions"
          - "Moq"
        update-types:
          - "minor"
          - "patch"
      analyzers:
        patterns:
          - "Microsoft.CodeAnalysis.*"
          - "SonarAnalyzer.*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "lukemurraynz"
    assignees:
      - "lukemurraynz"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"